### ISSUE TITLE
Error '_io.TextIOWrapper' object has no attribute 'reconfigure' for python 3.6

### ISSUE THREAD

**Issue by jacobtruman** [EnricoMi/publish-unit-test-result-action#247]
A recent change has introduced a failure for python < 3.7:

https://github.com/EnricoMi/publish-unit-test-result-action/blob/master/python/publish/github_action.py#L16

The `reconfigure` method was added in python 3.7, so causes issues when using python 3.6

```
Publish Unit Test Results
  Traceback (most recent call last):
    File "/home/runner/work/_actions/EnricoMi/publish-unit-test-result-action/v1/composite/../python/publish_unit_test_results.py", line 329, in <module>
      gha = GithubAction()
    File "/home/runner/work/_actions/EnricoMi/publish-unit-test-result-action/v1/python/publish/github_action.py", line 16, in __init__
      file.reconfigure(encoding='utf-8')
  AttributeError: '_io.TextIOWrapper' object has no attribute 'reconfigure'
  Error: Process completed with exit code 1.
```

**Comment by EnricoMi** [comment]
Python 3.6 has seen end of life Dec. 2021. So I think it is fair to say Python < 3.7 is not supported.

**Comment by bluesliverx** [comment]
CentOS 7 still has only Python 3.6.8 available in its repos, and will be maintained until 2024 (unfortunately).

https://en.wikipedia.org/wiki/CentOS#End-of-support_schedule

**Comment by EnricoMi** [comment]
This is sad. If this is the only place breaking for Python 3.6, than this should be easy to work around.

**Comment by EnricoMi** [comment]
Fix has been released. The action should work with Python 3.6 again.
